language: python
sudo: required
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- sudo apt-get -y install libmagic1
install:
- pip install coverage coveralls
- python bootstrap.py
- ./bin/buildout
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: rACDvytEiWQRVaqPqXJPMaq3G5b04VT1K/UNU7n1VhqCHCBNbT12ZKickfieOwALWacQT7ph3moyXrDlGUz1jYLO8aWkirzTP8tsfcud1za2ED8GDMxu8n5zUoEshN48glyeyGDN1PFBql1zwdQMhROLjFiHXYxP5LlqTXg28Yz08fhxpRbR10QzCyAu0Re+UninG1sXxm4gGwo/04DF6nnall/TtLko4Y9Oo4bO52Qxx9Pbr1W3vqj9Lp5iJWZiK0u6yDCZEOhJ2qoxUwVRcIK4o+CfbUR1Hfeo0aAz98KzQIrYWkRkkxjFyTxJ3WuGC5CKk8UhdfsLrY3I2xC++oFvviF3o8FpUuwP6qX99P3gtWtAyHg4DlHHHjGUMVAUnFIMUwCmvvEMNfYTjM1m4G2/iza61xJiJY9H5FLqXL9TmWncktERM62FqVNC0xYhWuNR4ljR1Ns3kfdfIQtx1RmaQzN9guoqb9y2xcQBsvx2oPQgdLYStrUdniyOy2Kd3WsamaqwYOGnJHI7ilvruBqs46cCYs5EpUaK6DdWdbjbRBZSkU8gA7rWSewTOFRKngZ36LiM6lu290CFunOqU/p+OfNYOcGVfeEKV/wL35914O5CGD2sCUvebVcq4kwv5CGMDClo51e++wTXa2kv9Byyz3TaC/ipcrRrfK0Zqz4=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
