language: python
sudo: required
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- sudo apt-get -y install libmagic1
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: A7/IyzYPLkuFB8YHjs/qnf02yIF2nPCDhOBVCtBeS4ikURvhRKTXH5oEgX4Jeozo6iJGS8Uj1zmnmN6RnUE8Y4EVkl6WIo8sWaWzMgf7nItnZ7CZKYqbtgpUYJrYvMIO2vJTr17Vhn4QeazjftFOjUyWcaYfc18S/6zoRoOl44+onNHJRmUVu44MiqHgflmTxaJQg2ZgPUoeosn5tnj9mHKT07BNIkC46ARK1ZUW/+L0nOIAAkuZ6uto30IIUZaaUYPPalzNJL0miPu4EkkOabB5CAiL4IJPxL+FGPzPslALH2vvL6thsz02XGvPYk+v2zODWfAgWgmQ9LBCQ5Zs7Wyb4ocbHFb0zFWGO56Aa1mIP/ziAqQgOnk0z/JKi9ifK0hxRklGRXM1h+UrHzkmo/k9Mj0pYcWQqqO+PT5V8gT9jCDM6PSEpkQi/9rBfo7re6DNhWxxeldn93Q3z/g5uBvCdnKYyKxNbkQ3rfNkW2qQcF+n6Nqzg0ow5c6z5OWqYBimrDWWlsjkJ2MUm4VfZDV0my9ddFPfG/wbD4y/FrF06zpIToadcfU1sVnym+B9f1j5111A2zzDGwPWkv5TkKP7WQ+Z9E1Ib7T36b1Ru4JkO3GqzOcyGOHtBvhlPQwl96W4b1e1JsIZjE+xa4JDsLXrnYJ4fLD68ONltdU/i3w=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
